# Generated by Django 2.0.5 on 2018-05-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoho_id', models.CharField(max_length=255)),
                ('chartmogul_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoho_id', models.CharField(max_length=255)),
                ('chartmogul_id', models.CharField(max_length=255)),
            ],
        ),
    ]
